### ISSUE TITLE
BUG: AttributeError: 'Text' object has no attribute '__keylist__'

### ISSUE THREAD

**Issue by damianbobrowski** [Dlubal-Software/RSTAB_Python_Client#27]
**Describe the bug**
I just updated RSTAB
Running working models on updated `RSTAB` application I got `AttributeError` when use `ResultTable` 

**To Reproduce**
use `ResultTables.NodesSupportForces`

**Screenshots**
```python
File "C:\Users\creoox_admin\Desktop\creoox-engineering-rstab-worker\examples\debug\result_tables_problem.py\debug_model.py", line 559, in collect_results_from_resultTableAPI
    nodal_support_forces = ResultTables.NodesSupportForces(CaseObjectType.E_OBJECT_TYPE_LOAD_CASE, load_case_id, node_id)
  File "C:\Users\creoox_admin\Desktop\creoox-engineering-rstab-worker\venv\lib\site-packages\RSTAB\Results\resultTables.py", line 911, in NodesSupportForces
    return ConvertResultsToListOfDct(model.clientModel.service.get_results_for_nodes_support_forces(loading_type.name, loading_no, object_no), include_base)
  File "C:\Users\creoox_admin\Desktop\creoox-engineering-rstab-worker\venv\lib\site-packages\RSTAB\Results\resultTables.py", line 39, in ConvertResultsToListOfDct
    params = GetResultTableParameters(results)
  File "C:\Users\creoox_admin\Desktop\creoox-engineering-rstab-worker\venv\lib\site-packages\RSTAB\Results\resultTables.py", line 22, in GetResultTableParameters
    params['row'] = list(set(params['row'] + i.row.__keylist__))
AttributeError: 'Text' object has no attribute '__keylist__'
```

**Desktop (please complete the following information):**
 - Version of WIN10 OS: [WIN 10 20H2]
 - Version of RSTAB 9.03.0005
 - Version of tool RSTAB==1.7.0

**Comment by heetrojivadiya** [comment]
Hello @damianbobrowski ,

it seems like this described bug is fixed in commit [662db22](https://github.com/Dlubal-Software/RSTAB_Python_Client/commit/662db225b3c79abbc9f8262e15c59e70b16892e3) on 07.09.2023. Please update latest version of code by updating from main branch. Alternatively, you can use latest version of RSTAB v1.08.0 which is released today. Let us know, if it will fix your issue or not. 

Thanks and best regards,
Heet Rojivadiya

**Comment by damianbobrowski** [comment]
Hello @heetrojivadiya

 works OK with `RSTAB==1.8.0`
 
 Thanks
